import{a as E,S as $,i as a}from"./assets/vendor-DuKcLXOA.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))t(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const d of o.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&t(d)}).observe(document,{childList:!0,subtree:!0});function n(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function t(r){if(r.ep)return;r.ep=!0;const o=n(r);fetch(r.href,o)}})();const M="https://pixabay.com/api/",u=15,B="56320794-31c479758a0ddef69c373babb";async function g(e,s=1){const n={key:B,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:u,page:s};return(await E.get(M,{params:n})).data}const h=".gallery",b="#load-more",L="#loader";let f=null;function P(){f||(f=new $(`${h} a`,{captionsData:"alt",captionDelay:250}))}function v(e){const s=document.querySelector(h);if(!s)return;const n=e.map(t=>`
      <a class="photo-card" href="${t.largeImageURL}">
        <img src="${t.webformatURL}" alt="${t.tags}" loading="lazy" />
        <div class="info">
          <p class="info-item"><b>Likes</b><span>${t.likes}</span></p>
          <p class="info-item"><b>Views</b><span>${t.views}</span></p>
          <p class="info-item"><b>Comments</b><span>${t.comments}</span></p>
          <p class="info-item"><b>Downloads</b><span>${t.downloads}</span></p>
        </div>
      </a>`).join("");s.insertAdjacentHTML("beforeend",n),P(),f.refresh()}function R(){const e=document.querySelector(h);e&&(e.innerHTML="")}function S(){const e=document.querySelector(L);e&&e.classList.add("is-visible")}function q(){const e=document.querySelector(L);e&&e.classList.remove("is-visible")}function w(){const e=document.querySelector(b);e&&e.classList.add("is-visible")}function l(){const e=document.querySelector(b);e&&e.classList.remove("is-visible")}let m="",i=1,c=0;const p=document.querySelector("#search-form"),y=document.querySelector("#load-more");p&&p.addEventListener("submit",O);y&&y.addEventListener("click",x);async function O(e){e.preventDefault();const n=p.elements.searchQuery.value.trim();if(!n){a.warning({title:"Warning",message:"Please enter a search query."});return}m=n,i=1,R(),l(),S();try{const t=await g(m,i);if(c=t.totalHits||0,!t.hits||t.hits.length===0){a.info({title:"No results",message:"No images found. Try another query."});return}v(t.hits),a.success({title:"Success",message:`Found ${c} images.`}),c>0&&i*u>=c?(l(),a.info({title:"End",message:"We're sorry, but you've reached the end of search results."})):i*u<c?w():l()}catch(t){a.error({title:"Error",message:t.message||"Request failed"})}finally{q()}}async function x(){i+=1,S();try{const e=await g(m,i);if(!e.hits||e.hits.length===0){l(),a.info({title:"End",message:"We're sorry, but you've reached the end of search results."});return}v(e.hits),i*u>=c?(l(),a.info({title:"End",message:"We're sorry, but you've reached the end of search results."})):w();const n=document.querySelector(".gallery"),{height:t}=n.firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}catch(e){a.error({title:"Error",message:e.message||"Request failed"})}finally{q()}}
//# sourceMappingURL=index.js.map
